### ISSUE TITLE
عدم اتصال به پوشه مخاطبین در پنل

### ISSUE THREAD

**Issue by persenel** [esradev/Farazsms-React#1]
با سلام و درود
احتراماً افزونه فراز اس ام اس به دفتذچه تلفن در پنل پیامکی متصل نمی شود.

**Comment by amkh432** [comment]
> با سلام و درود احتراماً افزونه فراز اس ام اس به دفتذچه تلفن در پنل پیامکی متصل نمی شود.

منم اول گول خوردم باید صفحه را یه بار رفرش کنی

**Comment by esradev** [comment]
hi
This issue has been resolved in the latest version. Please download the plugin from the WordPress site itself.
Download link: https://wordpress.org/plugins/farazsms/
