### ISSUE TITLE
عدم وجود منوی ارسال پیامک

### ISSUE THREAD

**Issue by amkh432** [esradev/Farazsms-React#2]
سلام
در نوارد ادمین منوی ارسال پیامک اضافه شده ولی وقتی میزنی چیزی وجود نداره

**Comment by amkh432** [comment]
ارسال پیامک به دفترچه تلفن خیلی مهم است

**Comment by esradev** [comment]
HI, This issue has been resolved in the latest version. Please download the plugin from the WordPress site itself.
Download link: https://wordpress.org/plugins/farazsms/
