### ISSUE TITLE
کار نکردن دکمه ذخیره تنظیمات + نپذیرفتن شماره تماس ادمین

### ISSUE THREAD

**Issue by 79ho3ein** [esradev/Farazsms-React#4]
با سلام

پس از بررسی اولیه تنظیمات این افزونه با چند مشکل مواجه شدم.

1- تداخل بخش اعلان وردپرس با دکمه ذخیره : https://prnt.sc/reTEjMiCXi5R

2- شماره تماس بنده با 0992 شروع میشه، اما زمانی که شماره رو وارد میکنم قبول نمیکنه و فقط 0911 رو قبول میکنه.

3- نمیدونم این مشکل مربوط به مورد دومه یا نه، اما در بخش تنظیمات، دکمه ذخیره اصلا کار نمیکنه.

4- داخل اکشن فرم المنتور، اگه گزینه **برای کاربر پیامک بفرستید** رو غیرفعال کنیم، گزینه **در دفترچه تلفن سیستم ذخیره کنید** هم پنهان میشه.
مثلا من میخوام نه برای ادمین پیامک ارسال بشه، نه برای کاربر. اما فقط شماره ارسالی کاربر داخل دفترچه ذخیره بشه. در حال حاضر این امکان پذیر نیست. لطفا اصلاح کنید.

با تشکر از افزونه عالیتون

**Comment by esradev** [comment]
HI. We will investigate this issue and make the necessary changes. Thank you for your participation.

**Comment by esradev** [comment]
First 3 of your bugs reported are fixed. Now currently working on the forth of them.

**Comment by esradev** [comment]
On the forth bug that you reported, there is no bug's there, you can simply on the send sms to user select (not of them) as option of how to send. so the sms will not send either by pattern or web service.
