### ISSUE TITLE
بخش کامنت

### ISSUE THREAD

**Issue by sajadrasa** [esradev/Farazsms-React#5]
سلام وقتی کاربر کامنت میذاره هنوز حتا تایید نشده یا جواب داده نشده اس ام اس میره براش که به کامنت شما پاسخ داده شد!

**Comment by esradev** [comment]
HI. We will investigate this issue and make the necessary changes. Thank you for your participation.

**Comment by esradev** [comment]
> سلام وقتی کاربر کامنت میذاره هنوز حتا تایید نشده یا جواب داده نشده اس ام اس میره براش که به کامنت شما پاسخ داده شد!

HI. We will investigate this issue and make the necessary changes. Thank you for your participation.

**Comment by esradev** [comment]
This problem was fixed.
